// Run with: node test/run.mjs
import assert from 'node:assert/strict';
import { buildScriptFrame, F3Parser, toHex } from '../js/protocol.js';
import { parseUtterance, isStop } from '../js/voice.js';

// Frame bytes from research/01-ble-protocol.md (generated by DrorSh build_script_frame).
assert.equal(toHex(buildScriptFrame('mbot2.forward(50,1)', 1, 0)),
  'f3 0c 19 00 28 00 01 00 13 00 6d 62 6f 74 32 2e 66 6f 72 77 61 72 64 28 35 30 2c 31 29 56 f4');
assert.equal(toHex(buildScriptFrame('cyberpi.get_battery()', 2, 1)),
  'f3 0e 1b 00 28 01 02 00 15 00 63 79 62 65 72 70 69 2e 67 65 74 5f 62 61 74 74 65 72 79 28 29 47 f4');

// Captured robot reply, split across two notifications.
const reply = Uint8Array.from('f3 03 10 00 28 01 01 00 0a 00 7b 22 72 65 74 22 3a 37 35 7d 61 f4'.split(' ').map((h) => parseInt(h, 16)));
const p = new F3Parser();
assert.deepEqual(p.feed(reply.slice(0, 7)), []);
const [r] = p.feed(reply.slice(7));
assert.equal(r.idx, 1); assert.equal(r.value, 75);

const cases = [
  ['vorwärts', 'move', { dir: 'forward' }, 1],
  ['fahr zurück 2 Sekunden', 'move', { dir: 'backward' }, 2],
  ['links', 'turn', { deg: -90 }],
  ['rechts 45 Grad', 'turn', { deg: 45 }],
  ['ein bisschen nach rechts', 'turn', { deg: 30 }],
  ['dreh dich um', 'turn', { deg: 180 }],
  ['Licht blau', 'led', { r: 0, g: 0, b: 255 }],
  ['Licht weiß', 'led', { r: 255, g: 255, b: 255 }],
  ['Licht aus', 'led', { r: 0, g: 0, b: 0 }],
  ['Stopp', 'stop', {}],
  ['halt', 'stop', {}],
  ['schneller', 'speed', { delta: 15 }],
  ['wie ist der Abstand', 'read', { sensor: 'distance' }],
  ['go forward 3 seconds', 'move', { dir: 'forward' }, 3],
  ['turn left', 'turn', { deg: -90 }],
];
for (const [text, cmd, args, drive] of cases) {
  const out = parseUtterance(text);
  assert.ok(out, `no parse for "${text}"`);
  assert.equal(out.cmd, cmd, text);
  assert.deepEqual(out.args, args, text);
  if (drive) assert.equal(out.drive, drive, text);
}
assert.equal(parseUtterance('Hallo Roboter'), null);
assert.ok(isStop('stopp'));
assert.ok(!isStop('vorwärts'));
console.log(`ok: protocol + ${cases.length} voice cases`);

// --- joystick mixing and drive stream (fake clock) ---
const { mixArcade, DriveStream, DRIVE } = await import('../js/drive.js');
const near = (a, b) => Math.abs(a - b) < 0.01;
assert.deepEqual(mixArcade(0.05, 0.05), [0, 0]);                         // deadzone
assert.ok(mixArcade(0, 1).every((v) => near(v, 1)));                      // full forward
assert.ok(near(mixArcade(1, 0)[0], DRIVE.spinCap) && near(mixArcade(1, 0)[1], -DRIVE.spinCap)); // capped spin
{
  const [l, r] = mixArcade(0.5, 0.5);
  assert.ok(l > r && r > 0, 'forward-right curve');
}

let now = 0;
performance.now = () => now;
const frames = [];
const fakeBus = {
  guard: false, lastDistance: { value: null, at: 0 },
  submit: async (c) => { frames.push([now, c.cmd, c.args]); return { ok: true }; },
  stop: async () => { frames.push([now, 'stop']); return { ok: true }; },
};
const ds = new DriveStream({ bus: fakeBus, maxRpm: () => 100 });
ds.set(1, 1);
clearInterval(ds.timer); // drive ticks by hand
const run = (ms) => { for (let t = 0; t < ms; t += 50) { now += 50; ds.tick(); } };
run(1000);
const drives = frames.filter((f) => f[1] === 'drive');
assert.equal(drives[0][2].left, 15, 'first step ramps at 300 RPM/s');
assert.equal(drives.at(-1)[2].left, 100, 'reaches target');
const gaps = drives.slice(1).map((f, i) => f[0] - drives[i][0]);
assert.ok(Math.max(...gaps) <= DRIVE.keepaliveMs + 50, 'keepalive below watchdog timeout');
frames.length = 0;
ds.release();
clearInterval(ds.timer); ds.timer = 1;
run(400);
const tail = frames.filter((f) => f[1] === 'drive').map((f) => f[2].left);
assert.equal(tail.at(-1), 0, 'ramps down to 0 on release');
assert.ok(tail.length >= 4, 'ramp down is gradual');

// obstacle guard scales forward throttle
fakeBus.guard = true;
fakeBus.lastDistance = { value: 27.5, at: Date.now() };
assert.ok(near(ds.guardFactor(), 0.5));
fakeBus.lastDistance = { value: 10, at: Date.now() };
assert.equal(ds.guardFactor(), 0);
console.log('ok: joystick mixing + drive stream');
